from pydantic import BaseModel, Field
from typing import Optional, List, Any


# ────────────────────────────────────────────
#  EVENTS
# ────────────────────────────────────────────

class TrackingEvent(BaseModel):
    """
    A single captured user interaction.
    Sent in batches from tracker.js every few seconds.
    """
    event_type: str = Field(
        ...,
        description="Type of event: 'mousemove', 'click', or 'scroll'"
    )
    x: Optional[float] = Field(
        None,
        description="Horizontal coordinate in pixels from left of viewport"
    )
    y: Optional[float] = Field(
        None,
        description="Vertical coordinate in pixels from top of viewport"
    )
    scroll_pct: Optional[float] = Field(
        None,
        description="Scroll depth as a percentage of total page height (0-100)"
    )
    viewport_w: Optional[int] = Field(
        None,
        description="Viewport width in pixels at time of event"
    )
    viewport_h: Optional[int] = Field(
        None,
        description="Viewport height in pixels at time of event"
    )
    timestamp: int = Field(
        ...,
        description="Unix timestamp in milliseconds"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "event_type": "click",
                "x": 540,
                "y": 320,
                "scroll_pct": 24.5,
                "viewport_w": 1440,
                "viewport_h": 900,
                "timestamp": 1712000000000
            }
        }


class EventBatch(BaseModel):
    """
    A batch of events sent together from one session on one page.
    tracker.js flushes a batch every 5 seconds to reduce network calls.
    """
    session_id: str = Field(
        ...,
        description="Unique ID generated by tracker.js for this browser session"
    )
    page_key: str = Field(
        ...,
        description="URL-safe slug identifying the page. e.g. 'home', 'about'"
    )
    events: List[TrackingEvent] = Field(
        ...,
        description="List of tracking events captured during this flush interval"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "session_id": "abc-123-xyz",
                "page_key": "home",
                "events": [
                    {
                        "event_type": "mousemove",
                        "x": 300,
                        "y": 150,
                        "scroll_pct": 0.0,
                        "viewport_w": 1440,
                        "viewport_h": 900,
                        "timestamp": 1712000000000
                    },
                    {
                        "event_type": "click",
                        "x": 720,
                        "y": 400,
                        "scroll_pct": 10.0,
                        "viewport_w": 1440,
                        "viewport_h": 900,
                        "timestamp": 1712000005000
                    }
                ]
            }
        }


# ────────────────────────────────────────────
#  SESSIONS
# ────────────────────────────────────────────

class SessionCreate(BaseModel):
    """
    A full rrweb session recording.
    Sent once when the user leaves or closes the page.
    """
    page_key: str = Field(
        ...,
        description="Page the session was recorded on"
    )
    duration_ms: Optional[int] = Field(
        None,
        description="Total session duration in milliseconds"
    )
    rrweb_events: List[Any] = Field(
        ...,
        description="Raw rrweb event stream — DOM snapshots and mutations"
    )
    user_agent: Optional[str] = Field(
        None,
        description="Browser user agent string"
    )
    screen_w: Optional[int] = Field(
        None,
        description="Full screen width in pixels"
    )
    screen_h: Optional[int] = Field(
        None,
        description="Full screen height in pixels"
    )

    class Config:
        json_schema_extra = {
            "example": {
                "page_key": "home",
                "duration_ms": 45000,
                "rrweb_events": [],
                "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
                "screen_w": 1920,
                "screen_h": 1080
            }
        }


# ────────────────────────────────────────────
#  RESPONSES
# ────────────────────────────────────────────

class StatusResponse(BaseModel):
    """Response shape for the /status endpoint."""
    status: str
    sessions: int
    events: int


class HeatmapPoint(BaseModel):
    """A single normalized coordinate point for heatmap rendering."""
    event_type: str
    x_pct: float
    y_pct: float
    x: float
    y: float
    viewport_w: int
    viewport_h: int


class HeatmapResponse(BaseModel):
    """Response shape for the /heatmap/{page_key} endpoint."""
    page: str
    points: List[HeatmapPoint]


class SessionMeta(BaseModel):
    """Session metadata without the full rrweb payload."""
    id: str
    page_key: str
    duration_ms: Optional[int]
    user_agent: Optional[str]
    screen_w: Optional[int]
    screen_h: Optional[int]
    created_at: str
    data_size_bytes: int